apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          command: ["redis-server", "--requirepass", "someredispassword"]
          volumeMounts:
            - name: redis-data  # Corrected volume name reference
              mountPath: /data
      volumes:
        - name: redis-data  # Add this volume definition
          persistentVolumeClaim:
            claimName: redis-data  # Ensure it matches the PVC name
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: expense-tracker
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: expense-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-class
