apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: annika1712/exp-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://a565845791c894e76998e0c93160db5e-847883130.ap-southeast-1.elb.amazonaws.com:8706"  # Backend service URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense-tracker
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
