apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: annika1712/exp-backend:1.0.0
          ports:
            - containerPort: 8706
          env:
            - name: PORT
              value: "8706"
            - name: DATABASE_URI
              value: "mongodb://root:example@mongodb:27017/"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PASSWORD
              value: "someredispassword"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense-tracker
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8706
      targetPort: 8706
  type: LoadBalancer
